### ISSUE TITLE
custom esbuild

### ISSUE THREAD

**Issue by eng-dibo** [just-jeb/angular-builders#1339] opened 2023-02-03 12:31 UTC
as you introduced the nice custom webpack feature, and as now Angular trends to use esbuild which is faster than webpack and more dynamic, I demand to also introduce custom-esbuild.

[more about supporting esbuild in Angular](https://blog.angular.io/angular-v15-is-now-available-df7be7f2f4c8)

**Comment by arturovt** [comment] 2023-02-07 10:57
Duplicate of #1288.

**Closed by arturovt** 2023-02-07 10:57 UTC
