### ISSUE TITLE
[Issue] Data path '' should NOT have additional properties (es5BrowserSupport) with `10.0.0` only

### ISSUE THREAD

**Issue by C0ZEN** [just-jeb/angular-builders#810] opened 2020-08-10 14:09 UTC
## Describe the Bug

I have this error:

`Data path '' should NOT have additional properties (es5BrowserSupport)`

When serving my Angular 10 application.
This is only an issue with the version `10.0.0` of `@angular-builders/custom-webpack` dependency.
Installing the version `9.2.0` of `@angular-builders/custom-webpack` fix the error.

## Expected Behavior

No error and the app start running.

## Environment

```
Libs
- @angular/core version: 10.0.8
- @angular-devkit/build-angular version: 0.1000.5
- @angular-builders/custom-webpack version: 9.2.0
```

I do not know if you are aware of this error and if not let me know if you need more information about my project.

**Comment by fnnzzz** [comment] 2020-08-10 16:05
I have a similar case with `@angular-builders/custom-webpack:server`
I get the error "Data path "" should NOT have additional properties(vendorChunk)."

**Environment:**
```
"@angular-builders/custom-webpack": "10.0.0"
"@angular/core": 10.0.8
"@angular-devkit/build-angular": "0.1000.5",
```

**Comment by just-jeb** [comment] 2020-08-11 10:10
Please take a look at #781 (specifically [this](https://github.com/just-jeb/angular-builders/issues/781#issuecomment-652476825) comment) and LMK if it helps.

**Comment by C0ZEN** [comment] 2020-08-11 10:52
@just-jeb I already tried to remove the package-lock, node_modules and reinstall everything and it did not change a thing.
I followed the exact same steps than [this comment](https://github.com/just-jeb/angular-builders/issues/781#issuecomment-652476825) because it was slightly different from what I did nevertheless the issue is still here 😢

**Comment by C0ZEN** [comment] 2020-08-11 11:05
Also after I discarded the upgrade of this dependency and ran `npm i` I had this new error when doing the serve: `ERROR in Cannot read property 'flags' of undefined`.
Note that after this the `package-lock.json` was still changed so there is also another problem in a peer dependency 😭 
But a clean remove and install of the node_modules fixed it.

**Comment by fnnzzz** [comment] 2020-08-11 12:51
I also tried to downgrade to version 9.2.0, got an error `ERROR in Cannot read property 'flags' of undefined`

**Comment by C0ZEN** [comment] 2020-08-11 12:54
@fnnzzz brothers in errors then 🥳

**Comment by slavoroi** [comment] 2020-08-24 12:05
I'm sorry, I have the same for :
```
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(allowedCommonJsDependencies).
```

with package.json:
```
"@angular-builders/custom-webpack": "10.0.0",
    "@angular-builders/dev-server": "7.3.1",
    "@angular-devkit/build-angular": "0.1000.7",
    "@angular-devkit/build-ng-packagr": "0.1000.7",
    "@angular/animations": "10.0.11",
    "@angular/cdk": "10.1.3",
    "@angular/cli": "10.0.7",
    "@angular/common": "10.0.11",
    "@angular/compiler": "10.0.11",
    "@angular/compiler-cli": "10.0.11",
    "@angular/core": "10.0.11",
    "@angular/forms": "10.0.11",
    "@angular/language-service": "10.0.11",
    "@angular/platform-browser": "10.0.11",
    "@angular/platform-browser-dynamic": "10.0.11",
    "@angular/router": "10.0.11",
    "@commitlint/cli": "9.1.2",
    "@commitlint/config-conventional": "9.1.2",
    "@cypress/code-coverage": "3.8.1",
    "@cypress/webpack-preprocessor": "5.4.4",
    "@istanbuljs/nyc-config-typescript": "1.0.1",
    "@ngx-translate/core": "13.0.0",
    "@semantic-release/git": "9.0.0",
    "@trax-retail/proxy-dev-agent": "1.4.1",
    "@trax-retail/web-components": "1.1.1",
    "@trax-retail/web-standards": "2.0.13",
    "@types/jasmine": "3.5.13",
    "@types/jasminewd2": "2.0.8",
    "@types/node": "14.6.0",
    "codelyzer": "6.0.0",
    "cypress": "5.0.0",
    "husky": "4.2.5",
    "istanbul-instrumenter-loader": "3.0.1",
    "istanbul-lib-coverage": "3.0.0",
    "jasmine-core": "3.6.0",
    "jasmine-spec-reporter": "5.0.2",
    "jssha": "3.1.2",
    "@types/jssha": "2.0.0",
    "jwt-decode": "2.2.0",
    "karma": "5.1.1",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage-istanbul-reporter": "3.0.3",
    "karma-jasmine": "4.0.1",
    "karma-jasmine-html-reporter": "1.5.4",
    "markdownlint-cli": "0.23.2",
    "nanoid": "3.1.12",
    "ng-lint-report": "0.1.11",
    "ng-packagr": "10.0.4",
    "ngx-cookie-service": "10.0.1",
    "ngx-translate-multi-http-loader": "3.0.0",
    "nyc": "15.1.0",
    "rxjs": "6.6.2",
    "scss-bundle": "3.0.2",
    "source-map-support": "0.5.19",
    "ts-loader": "8.0.3",
    "ts-node": "9.0.0",
    "tslib": "2.0.1",
    "tslint": "6.1.3",
    "typescript": "3.9.7",
    "zone.js": "0.11.1"
```

**Comment by fasidOnGit** [comment] 2020-08-31 08:22
+1

`Data path "" should NOT have additional properties(allowedCommonJsDependencies).`

package.json
```
...
 "@angular-builders/custom-webpack": "10.0.0",
 "@angular/cli": "10.0.8",
 "@angular/compiler-cli": "10.0.14",
...
```

**Comment by just-jeb** [comment] 2020-08-31 15:27
All these cases smell like some versions collision, would you mind running this:

`npm list @angular-devkit/build-angular`
`npm list @angular-devkit/architect`
`npm list @angular-devkit/core`

And posting the results here?

**Comment by slavoroi** [comment] 2020-08-31 15:28
this was fixed for me in rhe latest version update

**Comment by fasidOnGit** [comment] 2020-08-31 15:34
@just-jeb We are trying to update our project from v9 to v10. I did, the usual `ng update package-name` 

Here is the `npm list` command.

```
npm list @angular-devkit/core
[INFO] ├─┬ @angular-builders/custom-webpack@10.0.0
[INFO] │ ├─┬ @angular-devkit/architect@0.1000.8
[INFO] │ │ └── @angular-devkit/core@10.0.8  deduped
[INFO] │ └── @angular-devkit/core@10.0.8 
[INFO] ├─┬ @angular-devkit/build-angular@0.1000.8
[INFO] │ ├─┬ @angular-devkit/architect@0.1000.8
[INFO] │ │ └── @angular-devkit/core@10.0.8  deduped
[INFO] │ ├─┬ @angular-devkit/build-webpack@0.1000.8
[INFO] │ │ ├─┬ @angular-devkit/architect@0.1000.8
[INFO] │ │ │ └── @angular-devkit/core@10.0.8  deduped
[INFO] │ │ └── @angular-devkit/core@10.0.8 
[INFO] │ ├── @angular-devkit/core@10.0.8 
[INFO] │ └─┬ @ngtools/webpack@10.0.8
[INFO] │   └── @angular-devkit/core@10.0.8 
[INFO] └─┬ @angular/cli@10.0.8
[INFO]   ├─┬ @angular-devkit/architect@0.1000.8
[INFO]   │ └── @angular-devkit/core@10.0.8  deduped
[INFO]   ├── @angular-devkit/core@10.0.8 
[INFO]   ├─┬ @angular-devkit/schematics@10.0.8
[INFO]   │ └── @angular-devkit/core@10.0.8 
[INFO]   ├─┬ @schematics/angular@10.0.8
[INFO]   │ └── @angular-devkit/core@10.0.8 
[INFO]   └─┬ @schematics/update@0.1000.8
[INFO]     └── @angular-devkit/core@10.0.8 
```


```
npm list @angular-devkit/architect
[INFO] ├─┬ @angular-builders/custom-webpack@10.0.0
[INFO] │ └── @angular-devkit/architect@0.1000.8 
[INFO] ├─┬ @angular-devkit/build-angular@0.1000.8
[INFO] │ ├── @angular-devkit/architect@0.1000.8 
[INFO] │ └─┬ @angular-devkit/build-webpack@0.1000.8
[INFO] │   └── @angular-devkit/architect@0.1000.8 
[INFO] └─┬ @angular/cli@10.0.8
[INFO]   └── @angular-devkit/architect@0.1000.8 

```


```
npm list @angular-devkit/build-angular
[INFO] portal@0.0.1 /home/fasid/Work/ts2-psp-merge/ts2-portal
[INFO] ├─┬ @angular-builders/custom-webpack@10.0.0
[INFO] │ └── @angular-devkit/build-angular@0.1000.8  deduped
[INFO] └── @angular-devkit/build-angular@0.1000.8 
```

**Comment by just-jeb** [comment] 2020-09-01 07:05
@fasidOnGit OK, I don't see anything suspicious here, so I'm gonna need a reproduction.

**Comment by fnnzzz** [comment] 2020-09-01 07:19
I tried to update to newer versions of @angular/xxx, but the error did not disappear

```
npm list @angular-devkit/build-angular

├─┬ @angular-builders/custom-webpack@10.0.0
│ └── @angular-devkit/build-angular@0.1000.5 
└── @angular-devkit/build-angular@0.1000.8 
```

```
npm list @angular-devkit/architect

├─┬ @angular-builders/custom-webpack@10.0.0
│ ├── @angular-devkit/architect@0.1000.5 
│ └─┬ @angular-devkit/build-angular@0.1000.5
│   ├── @angular-devkit/architect@0.1000.5  deduped
│   └─┬ @angular-devkit/build-webpack@0.1000.5
│     └── @angular-devkit/architect@0.1000.5  deduped
├─┬ @angular-devkit/build-angular@0.1000.8
│ └── @angular-devkit/architect@0.1000.8 
├─┬ @angular-devkit/build-webpack@0.1000.8
│ └── @angular-devkit/architect@0.1000.8 
├─┬ @angular/cli@10.0.8
│ └── @angular-devkit/architect@0.1000.8 
├─┬ @nguniversal/builders@10.0.2
│ └── @angular-devkit/architect@0.1000.7 
├─┬ @nrwl/cypress@10.1.0
│ └── @angular-devkit/architect@0.1000.5  deduped
├─┬ @nrwl/jest@10.1.0
│ └── @angular-devkit/architect@0.1000.5  deduped
├─┬ @nrwl/schematics@9.0.0-beta.3
│ ├─┬ @nrwl/angular@9.0.0-beta.3
│ │ ├─┬ @nrwl/cypress@9.0.0-beta.3
│ │ │ └── @angular-devkit/architect@0.900.0-rc.5 
│ │ └─┬ @nrwl/jest@9.0.0-beta.3
│ │   └── @angular-devkit/architect@0.900.0-rc.5  deduped
│ └─┬ @nrwl/workspace@9.0.0-beta.3
│   └─┬ @nrwl/cli@9.0.0-beta.3
│     └─┬ @nrwl/tao@9.0.0-beta.3
│       └── @angular-devkit/architect@0.900.0-rc.5  deduped
└─┬ @nrwl/workspace@10.1.0
  └─┬ @nrwl/cli@10.1.0
    └─┬ @nrwl/tao@10.1.0
      └── @angular-devkit/architect@0.1000.5  deduped
```

```
npm list @angular-devkit/core

├─┬ @angular-builders/custom-webpack@10.0.0
│ ├─┬ @angular-devkit/architect@0.1000.5
│ │ └── @angular-devkit/core@10.0.5  deduped
│ ├─┬ @angular-devkit/build-angular@0.1000.5
│ │ ├─┬ @angular-devkit/build-webpack@0.1000.5
│ │ │ └── @angular-devkit/core@10.0.5  deduped
│ │ ├── @angular-devkit/core@10.0.5  deduped
│ │ └─┬ @ngtools/webpack@10.0.5
│ │   └── @angular-devkit/core@10.0.5  deduped
│ └── @angular-devkit/core@10.0.5 
├─┬ @angular-devkit/build-angular@0.1000.8
│ ├─┬ @angular-devkit/architect@0.1000.8
│ │ └── @angular-devkit/core@10.0.8  deduped
│ ├── @angular-devkit/core@10.0.8 
│ └─┬ @ngtools/webpack@10.0.8
│   └── @angular-devkit/core@10.0.8 
├─┬ @angular-devkit/build-webpack@0.1000.8
│ ├─┬ @angular-devkit/architect@0.1000.8
│ │ └── @angular-devkit/core@10.0.8  deduped
│ └── @angular-devkit/core@10.0.8 
├─┬ @angular/cli@10.0.8
│ ├─┬ @angular-devkit/architect@0.1000.8
│ │ └── @angular-devkit/core@10.0.8  deduped
│ ├── @angular-devkit/core@10.0.8 
│ ├─┬ @angular-devkit/schematics@10.0.8
│ │ └── @angular-devkit/core@10.0.8  deduped
│ ├─┬ @schematics/angular@10.0.8
│ │ ├── @angular-devkit/core@10.0.8 
│ │ └─┬ @angular-devkit/schematics@10.0.8
│ │   └── @angular-devkit/core@10.0.8  deduped
│ └─┬ @schematics/update@0.1000.8
│   ├── @angular-devkit/core@10.0.8 
│   └─┬ @angular-devkit/schematics@10.0.8
│     └── @angular-devkit/core@10.0.8  deduped
├─┬ @datorama/akita@4.23.0
│ └─┬ schematics-utilities@1.1.3
│   ├── @angular-devkit/core@7.3.9 
│   └─┬ @angular-devkit/schematics@7.3.9
│     └── @angular-devkit/core@7.3.9  deduped
├─┬ @nguniversal/builders@10.0.2
│ ├─┬ @angular-devkit/architect@0.1000.7
│ │ └── @angular-devkit/core@10.0.7  deduped
│ └── @angular-devkit/core@10.0.7 
├─┬ @nrwl/angular@10.1.0
│ ├─┬ @angular-devkit/schematics@10.0.5
│ │ └── @angular-devkit/core@10.0.5  deduped
│ └─┬ @schematics/angular@10.0.5
│   └── @angular-devkit/core@10.0.5  deduped
├─┬ @nrwl/cypress@10.1.0
│ └── @angular-devkit/core@10.0.5  deduped
├─┬ @nrwl/jest@10.1.0
│ └── @angular-devkit/core@10.0.5  deduped
├─┬ @nrwl/schematics@9.0.0-beta.3
│ ├─┬ @nrwl/angular@9.0.0-beta.3
│ │ ├─┬ @angular-devkit/schematics@9.0.0-rc.5
│ │ │ └── @angular-devkit/core@9.0.0-rc.5  deduped
│ │ ├─┬ @nrwl/cypress@9.0.0-beta.3
│ │ │ ├─┬ @angular-devkit/architect@0.900.0-rc.5
│ │ │ │ └── @angular-devkit/core@9.0.0-rc.5  deduped
│ │ │ └── @angular-devkit/core@9.0.0-rc.5  deduped
│ │ ├─┬ @nrwl/jest@9.0.0-beta.3
│ │ │ └── @angular-devkit/core@9.0.0-rc.5  deduped
│ │ └─┬ @schematics/angular@9.0.0-rc.5
│ │   └── @angular-devkit/core@9.0.0-rc.5  deduped
│ └─┬ @nrwl/workspace@9.0.0-beta.3
│   ├── @angular-devkit/core@9.0.0-rc.5 
│   └─┬ @nrwl/cli@9.0.0-beta.3
│     └─┬ @nrwl/tao@9.0.0-beta.3
│       └── @angular-devkit/core@9.0.0-rc.5  deduped
└─┬ @nrwl/workspace@10.1.0
  ├── @angular-devkit/core@10.0.5  deduped
  └─┬ @nrwl/cli@10.1.0
    └─┬ @nrwl/tao@10.1.0
      └── @angular-devkit/core@10.0.5  deduped


```

**Comment by fasidOnGit** [comment] 2020-09-01 09:06
@just-jeb Simple, the libraries that our project is using uses commonjs dependencies. as per angular doc here, https://angular.io/guide/build#configuring-commonjs-dependencies , we need to call out the libraries in `angular.json`. which I tried to add in my project that uses `"builder": "@angular-builders/custom-webpack:browser",`, Hence I arrive at the aforementioned problem https://github.com/just-jeb/angular-builders/issues/810#issuecomment-683639790.

I'll try to make a reproduction repository meanwhile.

**Comment by okansarica** [comment] 2021-02-11 12:58
Nothing yet? having the same issue

**Comment by guitarooman14** [comment] 2021-02-18 11:15
What I've found in documentation:

> Thus, if you use @angular-builders/custom-webpack:dev-server along with @angular-builders/custom-webpack:browser, ng serve will run with custom configuration provided in the latter.

`Example
angular.json:

"architect": {
  ...
  "build": {
    "builder": "@angular-builders/custom-webpack:browser",
    "options": {
      "customWebpackConfig": {
         "path": "./extra-webpack.config.js"
      },
      ...
    }
  },
  "serve": {
    "builder": "@angular-builders/custom-webpack:dev-server",
    "options": {
      "browserTarget": "my-project:build"
    }
  }`

**Comment by ndesimone** [comment] 2021-02-24 05:47
I'm on 10.2.2 and am having the same problem (listed in the title)

**Comment by tmushayahama** [comment] 2021-03-01 04:46
I am having the same problem with angular 11 as well. Any solution to this?

**Comment by martinsotirov** [comment] 2021-03-03 18:26
Same problem.

**Comment by Sieabah** [comment] 2021-03-05 08:55
Running in to similar issues with Angular 11.

Running [this](https://github.com/just-jeb/angular-builders/issues/781#issuecomment-652476825) doesn't change the error.

**Comment by MickL** [comment] 2021-03-08 12:17
Same error, cant set `allowedCommonJsDependencies` as described here: https://angular.io/guide/build#configuring-commonjs-dependencies :

> Schema validation failed with the following errors:
>   Data path "" should NOT have additional properties(allowedCommonJsDependencies).

Version:
```
Angular CLI: 11.2.3
Node: 15.6.0
OS: darwin x64

Angular: 11.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.3
@angular-devkit/build-angular   0.1102.3
@angular-devkit/core            11.2.3
@angular-devkit/schematics      11.2.3
@angular/cli                    11.2.3
@schematics/angular             11.2.3
@schematics/update              0.1102.3
ng-packagr                      11.2.4
rxjs                            6.6.3
typescript                      4.0.7

```

**Comment by jgutix** [comment] 2021-03-09 05:52
Look for that property `es5BrowserSupport` on your angular.json file and remove it.

In general the compiler is telling you that it doesn't recognize the mentioned property, so in the case of: `Data path "" should NOT have additional properties(vendorChunk).`, the `vendorChunk` property is not recognized and should be removed or replaced with a correct value.

**Comment by just-jeb** [comment] 2021-03-21 13:23
Guys, anyone who's facing this problem - please provide a minimal reproduction repo. It's very hard to help you without it, because the error is very generic and any mismatch in `angular.json` schema can cause this behavior.

**Comment by marselbeqiri** [comment] 2021-04-03 22:37
If you guys having the above error with 'es5BrowserSupport ' specified. 

At 'angular.json' go: 
**projects.ng-complete-guide-update.architect.build.options** and delete property" **es5BrowserSupport : true**"

because Property 'es5BrowserSupport' is not allowed

**Comment by just-jeb** [comment] 2021-04-04 11:08
I'm closing this issue for now. Anyone who's facing it and is unable to fix it with any solution from the thread is welcome to provide a minimal reproduction.

**Closed by just-jeb** 2021-04-04 11:08 UTC
Labels: awaiting-reply, blocked, builders:custom-webpack

**Comment by chaimite** [comment] 2021-04-09 18:24
I update from angular 9.1 to 10.2. I was also seeing this problem when I was trying to add "allowedCommonJsDependencies" in angular.json. 
The ways I solved was by updating "@angular-builders/custom-webpack" to 10.0.1.
I hope this helps other people facing the same issue.

**Comment by martinsotirov** [comment] 2021-04-21 21:42
> repro

I managed to extract a minimal build from our app that reproduces the bug: https://github.com/martinsotirov/angular-builders-webpack-bug. I hope this helps in debugging the problem.

**Comment by szywi** [comment] 2021-04-28 09:06
For those struggling with `Data path "" should NOT have additional properties(customWebpackConfig).`:

Make sure you configure `customWebpackConfig` with `@angular-devkit/build-angular:browser` (and not `@angular-builders/custom-webpack:dev-server`).

See: [custom-webpack-dev-server](https://www.npmjs.com/package/@angular-builders/custom-webpack#custom-webpack-dev-server) for more.

**Comment by martinsotirov** [comment] 2021-04-28 09:43
> Make sure you configure `customWebpackConfig` with `@angular-devkit/build-angular:browser` (and not `@angular-builders/custom-webpack:dev-server`).
@szywi I tried switching out `@angular-builders/custom-webpack:browser` for `@angular-devkit/custom-webpack:dev-server` but then it says:
```
An unhandled exception occurred: Cannot find module '@angular-devkit/custom-webpack/package.json'
```

**Comment by szywi** [comment] 2021-04-28 11:22
@martinsotirov I copied wrong builder, I'm sorry... Please check my updated answer :)

Basically what I meant is this part here in `angular.json` is most likely causing you troubles (it was the case in our project):
```
"serve": {
          "builder": "@angular-builders/custom-webpack:dev-server",
          "options": {
            "customWebpackConfig": { 
              "path": "./webpack.config.js"
            }
          },
```
Remove `customWebpackConfig` section and configure it in `build` target with `@angular-devkit/custom-webpack:browser` and it should work (at least you won't be getting those `Data path "" should NOT have additional properties(customWebpackConfig).`  errors anymore)

**Comment by martinsotirov** [comment] 2021-04-28 11:49
That did indeed remove the `Data path "" should NOT have additional properties(customWebpackConfig).` error. Thanks @szywi . 👍
Now I have to figure out what all the `postcss-loader` errors I get are about.

**Comment by vlanz** [comment] 2021-07-12 11:59
In my case, the problem was a leftover configuration statement from my previous tslint configuration in `angular.json` lint options.

Before: 
```
"lint": {
          "builder": "@angular-eslint/builder:lint",
          "options": {
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
```

After: 
```
"lint": {
          "builder": "@angular-eslint/builder:lint",
          "options": {
            "lintFilePatterns": [
              "src/**/*.ts",
              "src/**/*.html"
            ]
          }
        }
```

**Comment by SonicWim** [comment] 2022-12-02 22:40
I ended up here because it was the first Github hit for this error when trying to run some Udemy.com Angular tutorial code.
Using Visual Studio Code and the instructions are unpack, `npm i` and `ng serve` but it's never that simple... :-p
Too bad deprecated settings in angular.json are not picked up by the framework, or should this be VBCode's job?

But thanks @marselbeqiri  for the tip!

**Comment by matheo** [comment] 2024-04-27 04:50
I found out that I was using the wrong target in `serve` and getting this error
`path ''` means the config doesn't exist so the misconfigured angular.json is pointing to an empty target I guess
