### ISSUE TITLE
File not found: .../tsconfig.spec.json

### ISSUE THREAD

**Issue by telion2** [just-jeb/angular-builders#451] opened 2019-08-19 10:23 UTC
**Describe the bug**
Went through the steps of the readme and this website: https://codeburst.io/angular-6-ng-test-with-jest-in-3-minutes-b1fe5ed3417c
hit `ng test` 
got this error: 
```
 Test suite failed to run

    File not found: C:\Medieninformaitk\Medieninformatik\BA\Code\ConChat\conchatview\tsconfig.spec.json (resolved as: C:\Medieninformaitk\Medieninformatik\BA\Code\ConChat\conchatview\tsc
onfig.spec.json)

      at ConfigSet.resolvePath (../../../node_modules/ts-jest/dist/config/config-set.js:712:19)
      at ConfigSet.get (../../../node_modules/ts-jest/dist/config/config-set.js:204:67)
      at ConfigSet.tsJest (../../../node_modules/ts-jest/dist/util/memoize.js:43:24)
      at ConfigSet.get (../../../node_modules/ts-jest/dist/config/config-set.js:299:41)
      at ConfigSet.versions (../../../node_modules/ts-jest/dist/util/memoize.js:43:24)
      at ConfigSet.get (../../../node_modules/ts-jest/dist/config/config-set.js:583:32)
      at ConfigSet.jsonValue (../../../node_modules/ts-jest/dist/util/memoize.js:43:24)
      at ConfigSet.get [as cacheKey] (../../../node_modules/ts-jest/dist/config/config-set.js:598:25)
      at TsJestTransformer.getCacheKey (../../../node_modules/ts-jest/dist/ts-jest-transformer.js:126:36)
      at ScriptTransformer._getCacheKey (../../../node_modules/@jest/transform/build/ScriptTransformer.js:266:23)
``` 

What should I do? 
the tsconfic.spec.json is

**Comment by marcalj** [comment] 2019-08-21 11:39
Same problem, it's not detecting the file under ```src/``` folder.

**Comment by just-jeb** [comment] 2019-08-30 15:00
Yeah. Currently the only solution is to move the tsconfig to the root.  
I aligned with the Angular 8 file structure assuming they'll move all the necessary files as part of migration process (`ng update`). However that's not happening.  
I already have an open [issue](https://github.com/just-jeb/angular-builders/issues/338) to fix this, you are welcome to contribute (it's really small). Otherwise you'll have to wait until I get to this.

**Comment by just-jeb** [comment] 2019-08-30 15:02
Closing this as a duplicate if you are fine with that. Let me know if you're not.

**Closed by just-jeb** 2019-08-30 15:02 UTC
Labels: builders:jest

**Comment by youssefproject** [comment] 2020-06-12 15:10
i still have this issue

**Comment by just-jeb** [comment] 2020-06-18 12:28
@youssefproject the issue is solved, you can use `tsConfig` path in [options](https://github.com/just-jeb/angular-builders/tree/master/packages/jest#builder-options).
