### ISSUE TITLE
Budget option with type anyComponentStyle not supported

### ISSUE THREAD

**Issue by amiteshhh** [just-jeb/angular-builders#449] opened 2019-08-17 09:34 UTC
**Describe the bug**
Schema validation error is thrown when I tried using budget type **anyComponentStyle**

>Schema validation failed with the following errors:
  Data path ".budgets[1].type" should be equal to one of the allowed values.

**To Reproduce**
Add following in `angular.json` and setup custom-webpack
```javascript
"budgets": [//part of angular.json
...
  {
    "type": "anyComponentStyle",
    "maximumWarning": "6kb",
    "maximumError": "10kb"
  }
]
```

**Expected behavior**
All budget options which is supported by `@angular-devkit/build-angular` should be supported by custom web-pack.

https://github.com/angular/angular-cli/blob/master/packages/angular/cli/lib/config/schema.json

**Screenshots**
NA

**Builder:**
 - The name of the builder: `@angular-builders/custom-webpack`
 - The version of the builder: `8.1.0`

**Libraries**
 - `angular-devkit/build-angular`: 0.802.1

**Additional context**
When I inspected **node_modules\@angular-builders\custom-webpack\dist\browser\schema.json**, it was allowing below values only
```javascript
"enum": [
  "all",
  "allScript",
  "any",
  "anyScript",
  "bundle",
  "initial"
]
```

**Comment by just-jeb** [comment] 2019-08-17 13:15
Duplicate of #444

**Closed by just-jeb** 2019-08-17 13:15 UTC
