### ISSUE TITLE
Angular 11 + @angular-builders/custom-webpack + InjectPlugin error

### ISSUE THREAD

**Issue by Necroskillz** [just-jeb/angular-builders#882] opened 2020-11-19 16:41 UTC
## Describe the Bug

Using `InjectPlugin` now throws an error after updating to Angular 11.

## Minimal Reproduction

https://github.com/Necroskillz/custom-webpack-inject-repro

```
PS C:\Devel\tns\test\wpir\app> ng serve
√ Browser application bundle generation complete.

Initial Chunk Files   | Names         |      Size
vendor.js             | vendor        |   2.65 MB
polyfills.js          | polyfills     | 481.55 kB
styles.css, styles.js | styles        | 341.12 kB
main.js               | main          |  60.02 kB
runtime.js            | runtime       |   6.15 kB

                      | Initial Total |   3.52 MB

Build at: 2020-11-19T16:31:07.172Z - Hash: e497e022e83f982c96e1 - Time: 6774ms

Error: multi (webpack)-dev-server/client?http://0.0.0.0:0&sockPath=/sockjs-node (webpack)-inject-plugin/dist/webpack-inject-plugin.loader?id=webpack-inject-module-1 ./src/main.ts
Module not found: TypeError: Cannot read property 'descriptionFileData' of undefined

Error: multi (webpack)-dev-server/client?http://0.0.0.0:0&sockPath=/sockjs-node (webpack)-inject-plugin/dist/webpack-inject-plugin.loader?id=webpack-inject-module-1 ./src/polyfills.ts
Module not found: TypeError: Cannot read property 'descriptionFileData' of undefined

Error: multi (webpack)-dev-server/client?http://0.0.0.0:0&sockPath=/sockjs-node (webpack)-inject-plugin/dist/webpack-inject-plugin.loader?id=webpack-inject-module-1 ./src/styles.scss
Module not found: TypeError: Cannot read property 'descriptionFileData' of undefined
```

## Expected Behavior

No error.

## Environment

<pre><code>
Libs
- @angular/core version: 11.0.1
- @angular-devkit/build-angular version: 0.1100.2
- @angular-builders/custom-webpack version: 11.0.0-beta.1

For Tooling issues:
- Node version: v12.18.3  
- Platform:  Windows

Others:

</code></pre>

## Additional Context

I tried to find out where `descriptionFileData` is being accessed. It's only a few places that use this property, but I wasn't able to find the one where it throws.

**Comment by just-jeb** [comment] 2020-11-21 23:50
HI @Necroskillz , thanks for the detailed description. I'm not sure, however, how I can help here (apart from helping you to debug it). The plugin is invoked, that means that the Custom Webpack Builder does his job.  
After a quick glance at InjectPlugin and Angular code I'd bet on problem coming form Angular. Specifically from one of these two files: 
- https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/webpack/plugins/dedupe-module-resolve-plugin.ts
- https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_optimizer/src/build-optimizer/webpack-plugin.ts

They are the only ones that use `descriptionFileData`.  
You can check it by going into `node_modules/angular-devkit` and adding `console.log` in places where `descriptionFileData` is used.  
If the problem is there then you should probably open an issue for Angular CLI. If not, well debugging needed 😄 .

**Comment by Necroskillz** [comment] 2020-11-23 21:46
You are right, it's the dedupe module. I thought I checked it before, but apparently not deeply enough.

This is the case when it's undefined, not sure if this should be solved on the side of CLI or webpack-inject-plugin, but I moved the stuff to index-html transform to avoid this :P feel free to close this.
```
{
  context: 'C:\\Devel\\tns\\tns-app',
  request: 'C:\\Devel\\tns\\tns-app\\node_modules\\webpack-inject-plugin\\dist\\webpack-inject-plugin.loader.js?id=webpack-inject-module-1!',
  dependencies: [
    SingleEntryDependency {
      module: null,
      weak: false,
      optional: false,
      loc: [Object],
      request: 'C:\\Devel\\tns\\tns-app\\node_modules\\webpack-inject-plugin\\dist\\webpack-inject-plugin.loader?id=webpack-inject-module-1!',
      userRequest: 'C:\\Devel\\tns\\tns-app\\node_modules\\webpack-inject-plugin\\dist\\webpack-inject-plugin.loader?id=webpack-inject-module-1!'
    }
  ],
  userRequest: 'C:\\Devel\\tns\\tns-app\\node_modules\\webpack-inject-plugin\\dist\\webpack-inject-plugin.loader.js?id=webpack-inject-module-1!',
  rawRequest: 'C:\\Devel\\tns\\tns-app\\node_modules\\webpack-inject-plugin\\dist\\webpack-inject-plugin.loader?id=webpack-inject-module-1!',
  loaders: [
    {
      loader: 'C:\\Devel\\tns\\tns-app\\node_modules\\webpack-inject-plugin\\dist\\webpack-inject-plugin.loader.js',
      options: 'id=webpack-inject-module-1'
    }
  ],
  resource: '',
  matchResource: undefined,
  resourceResolveData: undefined,
  settings: { type: 'javascript/auto', resolve: {} },
  type: 'javascript/auto',
  parser: Parser {
    _pluginCompat: SyncBailHook {
      _args: [Array],
      taps: [Array],
      interceptors: [],
      call: [Function: lazyCompileHook],
      promise: [Function: lazyCompileHook],
      callAsync: [Function: lazyCompileHook],
      _x: undefined
    },
    hooks: {
      evaluateTypeof: [HookMap],
      evaluate: [HookMap],
      evaluateIdentifier: [HookMap],
      evaluateDefinedIdentifier: [HookMap],
      evaluateCallExpressionMember: [HookMap],
      statement: [SyncBailHook],
      statementIf: [SyncBailHook],
      label: [HookMap],
      import: [SyncBailHook],
      importSpecifier: [SyncBailHook],
      export: [SyncBailHook],
      exportImport: [SyncBailHook],
      exportDeclaration: [SyncBailHook],
      exportExpression: [SyncBailHook],
      exportSpecifier: [SyncBailHook],
      exportImportSpecifier: [SyncBailHook],
      varDeclaration: [HookMap],
      varDeclarationLet: [HookMap],
      varDeclarationConst: [HookMap],
      varDeclarationVar: [HookMap],
      canRename: [HookMap],
      rename: [HookMap],
      assigned: [HookMap],
      assign: [HookMap],
      typeof: [HookMap],
      importCall: [SyncBailHook],
      call: [HookMap],
      callAnyMember: [HookMap],
      new: [HookMap],
      expression: [HookMap],
      expressionAnyMember: [HookMap],
      expressionConditionalOperator: [SyncBailHook],
      expressionLogicalOperator: [SyncBailHook],
      program: [SyncBailHook],
      hotAcceptCallback: [SyncBailHook],
      hotAcceptWithoutCallback: [SyncBailHook]
    },
    options: {},
    sourceType: 'auto',
    scope: undefined,
    state: undefined,
    comments: undefined
  },
  generator: JavascriptGenerator {},
  resolveOptions: {}
}
```

**Comment by just-jeb** [comment] 2020-11-24 07:28
Hey @Necroskillz, thanks for letting me know. I'm closing this but I recommend you to open an issue in Angular CLI, seems like they need to add a null check there.

**Closed by just-jeb** 2020-11-24 07:28 UTC
