### ISSUE TITLE
ERROR in Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by vedran-m** [just-jeb/angular-builders#712] opened 2020-04-01 16:00 UTC
## Describe the Bug

Can't build the starter cli project with ng build after using `"builder": "@angular-builders/custom-webpack:browser"` as it returns the error:
`ERROR in Cannot read property 'flags' of undefined`

## Minimal Reproduction

1. Created an empty Angular app using latest (9.1.0) CLI following the guilde on https://angular.io/cli SASS was chosen as the style sheet library.
2. Replaced the builder with `"builder": "@angular-builders/custom-webpack:browser"`
3. Ran `ng build`

## Expected Behavior

Expected the app to build

## Environment

<pre><code>
Libs
- @angular/core version: 9.1.0
- @angular-devkit/build-angular version: 0.901.0
- @angular-builders/{the name of the builder} version: 9.0.0

For Tooling issues:
- Node version: v10.15.0  
- Platform:  Windows 

Others:

</code></pre>

**Comment by just-jeb** [comment] 2020-04-01 17:09
Duplicate of #708

**Closed by just-jeb** 2020-04-01 17:09 UTC

**Comment by vedran-m** [comment] 2020-04-02 07:52
Tried the beta, fixes the issue.
