### ISSUE TITLE
@angular-builders/custom-webpack Unknown argument "serve/build/etc.." when running ng commands

### ISSUE THREAD

**Issue by maranmaran** [just-jeb/angular-builders#1267] opened 2022-09-28 07:03 UTC
## Describe the Bug

Hey guys, I'm not sure if this is bug or caused by me, but you may be able to help me.

I have updated angular recently from 12 to 14 and when running serve I get the error message Unknown argument "serve" and serving gets stuck in "phase: setup".

This is true for all ng options
"unknown argument build"
"unknown argument serve" 
etc etc

I've just ran ncu -u, npm install that's all, I don't see any obvious problems reading documentation.

If I change back to @angular-devkit build passes successfully.

## Minimal Reproduction

Package json
```
  "dependencies": {
    "@alduino/humanizer": "^1.1.0",
    "@angular/animations": "~14.2.3",
    "@angular/cdk": "^14.2.2",
    "@angular/common": "~14.2.3",
    "@angular/compiler": "~14.2.3",
    "@angular/core": "~14.2.3",
    "@angular/forms": "~14.2.3",
    "@angular/material": "^14.2.2",
    "@angular/platform-browser": "~14.2.3",
    "@angular/platform-browser-dynamic": "~14.2.3",
    "@angular/router": "~14.2.3",
    "@microsoft/signalr": "^6.0.9",
    "@ngneat/hot-toast": "^4.1.0",
    "@ngneat/overview": "^3.0.4",
    "@ngneat/tailwind": "^7.0.3",
    "@types/dotenv": "^8.2.0",
    "@types/fs-extra": "^9.0.13",
    "@types/humanize-string": "^2.0.2",
    "@types/lodash": "^4.14.185",
    "@types/string-replace-webpack-plugin": "^0.1.3",
    "@types/yargs": "^17.0.13",
    "angu": "^0.12.0",
    "date-fns": "^2.29.3",
    "dotenv": "^16.0.2",
    "fs-extra": "^10.1.0",
    "humanize-string": "^3.0.0",
    "lodash": "^4.17.21",
    "material-design-icons-iconfont": "^6.7.0",
    "ng-dynamic-component": "^10.5.1",
    "rxjs": "~7.5.6",
    "string-replace-webpack-plugin": "^0.1.3",
    "tslib": "^2.4.0",
    "yargs": "^17.5.1",
    "zone.js": "~0.11.8"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^14.0.1",
    "@angular-devkit/architect": "0.1402.3",
    "@angular/cli": "~14.2.3",
    "@angular/compiler-cli": "~14.2.3",
    "tailwindcss": "^3.1.8",
    "tslint": "~6.1.0",
    "typescript": "4.8.3"
  }
```

angular json
```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "atm-tool": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "./webpack.config.js"
            },
            "allowedCommonJsDependencies": [
              "angu"
            ],
            "outputPath": "dist/atm-tool",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [],
            "vendorChunk": true,
            "extractLicenses": false,
            "buildOptimizer": false,
            "sourceMap": true,
            "optimization": false,
            "namedChunks": true
          },
          "configurations": {
            "production": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ]
            },
            "development": {
              "optimization": false,
              "outputHashing": "none",
              "sourceMap": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false
            },
            "local": {}
          },
          "defaultConfiguration": "development"
        },
        "serve": {
          "builder": "@angular-builders/custom-webpack:dev-server",
          "options": {
            "browserTarget": "atm-tool:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "atm-tool:build:production"
            },
            "development": {
              "browserTarget": "atm-tool:build:local"
            }
          }
        },
        "lint": {
          "builder": "@angular-builders/custom-webpack:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json",
              "e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "cli": {
    "analytics": false
  }
}
```

## Expected Behavior

Build should be successful

**Comment by just-jeb** [comment] 2022-10-19 16:51
Hi, could you please create a repository with minimal reproduction?

**Comment by just-jeb** [comment] 2022-11-02 23:20
This package does not define a specific requirement for host Angular version. Should work as long as it's v14. Try removing package-lock and running `install` again to regenerate it.

**Comment by arturovt** [comment] 2022-11-11 20:22
@maranmaran any progress on the reproducible example?

**Comment by maranmaran** [comment] 2022-11-11 20:32
Sorry folks, thanks for reminding me.

I was able to go around this by updating my npm registry and running npm install if I remember correctly.

Can you confirm this @nlapshin ?

**Comment by arturovt** [comment] 2022-11-30 15:40
Alright, closing the issue for now as not reproducible.

Let me know if the issue is happening again on your side, but that would be helpful to provide a reproducible example. I ain't able to understand what's really happening on your side w/o seeing the actual code.

**Closed by arturovt** 2022-11-30 15:40 UTC
