### ISSUE TITLE
[jest] upgrading to Angular 13 throws errors

### ISSUE THREAD

**Issue by matheo** [just-jeb/angular-builders#1204] opened 2022-05-11 01:32 UTC
## Describe the Bug

I'm trying to upgrade a website and the only broken ones are the tests :(

I've figured out to compile my testing utilities to `es2020` and to follow the [upgrade instructions](https://thymikee.github.io/jest-preset-angular/docs/guides/angular-13+/) of `jest-preset-angular` but I'm facing this blocker:
![image](https://user-images.githubusercontent.com/260185/167750325-2b94820e-d512-474e-88c3-c3f2444134ca.png)

## Expected Behavior

To run `ng test` successfully again.
@just-jeb can you help me to figure out what do I need to avoid this error?

## Environment

<pre><code>
Libs
- @angular/core version: ~13.3.6
- @angular-devkit/build-angular: ~13.3.5
- @angular-builders/custom-webpack: ~13.1.0
- @angular-builders/jest: ~13.0.4-beta.0
- jest-preset-angular: 11.1.1
- jest: 27.5.1

For Tooling issues:
- Node version: v16.15.0
- Platform:  Ubuntu
</code></pre>

**Comment by just-jeb** [comment] 2022-05-11 10:37
Unfortunately `mjs` is not yet supported by `@angular-builders/jest`. It should be addressed and implemented properly like it was done with [`custom-webpack`](https://github.com/just-jeb/angular-builders/commit/9d8cd2d9a5ee8ad859c2b89203e6450c4be16502).   
That means: 
 - Defining the API (there should be a switch that enables/disables ESM support, in order to support both CommonJs and ESM).
 - Implementing the changes in code (`imports` instead of `require`, default `.mjs` imports from setup files etc.)
 - Testing (having an E2E app that uses Jest builder in `ESM` mode)

That's not a huge amount of work, especially given there is already a good example from `custom-webpack`, but it still requires time.  
It definitely should be supported and I'll try to get to this ASAP, but there are more important things (like v14 upgrade that is coming), so we're open for contributions 😄.

**Comment by matheo** [comment] 2022-05-11 15:01
OMG, I see the custom `esm` and `cjs` settings in that PR,
can we handle those by default on `@angular-builders/jest`?
for v13 what are the requirements if I'm getting blocked by `jest-runtime`?
can I apply a workaround?

Thanks in advance @just-jeb!

**Comment by matheo** [comment] 2022-05-11 17:24
I've tried the `jest-preset-angular` esm example
but my v12 bundles requiring the `@angular/core` files instead importing are another blocker.

I do need to run CommonJS and ESM at the same time
with some indications I could help with this development,
can you give me some hints @just-jeb?

**Comment by just-jeb** [comment] 2022-05-12 06:36
I doubt it's possible to have ESM and CommonJS at the same time. Your app can be either CommonJS or ESM but not both of them.

**Comment by matheo** [comment] 2022-07-22 23:53
@just-jeb @ahnpnl We're having this issue now:

![image](https://user-images.githubusercontent.com/260185/180578471-9c72d1b6-07cf-446c-b994-5c5aca4b945e.png)

We have `@angular v12` packages trying to extend the classes from `@angular/core v13` mjs
I wonder if we can consume the available `esm2015` bundles in our v12 packages with the ng-jest-resolver :thinking: 

```typescript
import { HttpClient, HttpHandler, HttpHeaders } from '@angular/common/http';
import { Inject, Injectable } from '@angular/core';

@Injectable()
export class HttpService extends HttpClient {
```

FYI we're trying `nx@14.1.10` with `jest@27.5.1` but I might try `jest@latest` if you guys recommend me that.
Thanks in advance!

**Comment by arturovt** [comment] 2022-12-01 15:58
Closing until a reproducible example provided. It's really hard to judge what's wrong on your side since we're not seeing your code...

Feel free to re-open once a reproducible example. We're then able to look and debug it.

**Closed by arturovt** 2022-12-01 15:58 UTC
