### ISSUE TITLE
Using @angular-builder/custom-webpack to change a webpack property for Angular 13 isn't working

### ISSUE THREAD

**Issue by abf7d** [just-jeb/angular-builders#1289] opened 2022-10-21 19:01 UTC
## Describe the Bug
I need to add 'jsx' to resolve.extensions from my angluar application's webpack. After installing the @angular-builders/custom-webpack package, modifying the angular.json, and adding a custom webpack config file the application runs but the webpack change isn't registered. If I try to import a jsx file and exlude the extension, I get an error.

Details:
I am building an Angular 13 application alongside a react library via a NX monorepo. This react library uses jsx files. When I run my app, the React library files don't resolve the jsx extension correctly (all of the import statements for jsx files need to end in '.jsx'). tsx import correctly. I believe this is due to the configuration for webpack for my application. To solve this I need to add 'jsx' to the resolve.extensions array in webpack config. To do this I am using angular-builder's custom webpack package. 

## Minimal Reproduction

1. Clone my repo: from https://github.com/abf7d/render/tree/custom-webpack: `git clone https://github.com/abf7d/render.git`
2. Change directories to the repo: `cd render`
3. checkout custom-webpack branch: `git checkout custom-webpack`
4. run `npm install`
5. run the app: `npm start render-ui --app --watch`
6. Observe the error: `./libs/viv-viewer/src/index.ts:3:0-50 - Error: Module not found: Error: Can't resolve './lib/viv-viewer-web-comp-wrapper' in 'C:\render\libs\viv-viewer\src'`

## Expected Behavior
Since I have added a custom webpack config (that adds jsx to resolve.extensions) in the root folder and have modified my angular.json file to use the custom-webpack builder, I expect that the .jsx extension is resolved and that is no error happens when I serve the app.

What I have done:
1. Create an nx repo with an angular app and react library
1. Install custom-webpack package: `npm install --save-dev @angular-builders/custom-webpack@13`
2. Created a custom-webpack.config.js file in the application root with the following contents:
```
module.exports = {
    resolve: {
        extensions: ['', '.tsx', '.ts', '.js','min.js', 'jsx']
      }
  };
```
3. Replaced architect.build.builder in the angular json:
`"builder": "@angular-devkit/build-angular:browser"` changed to `"builder": "@angular-builders/custom-webpack:browser"` I added the following to architect.build.options:
```
"customWebpackConfig": {
  "path": "custom-webpack.config.js",
  "replaceDuplicatePlugins": true
},
```
4. Changed architect.serve.builder from `"builder": "@angular-devkit/build-angular:dev-server"` to `"builder": "@angular-builders/custom-webpack:dev-server"`

## Environment

<pre><code>
Libs
- @angular/core version: ~13.1.0
- @angular-devkit/build-angular version: ~13.1.0
- @angular-builders/custom-webpack:browser: ~13.1.0

For Tooling issues:
- Node version: 12.22.12
- Platform:  Windows

Others:

</code></pre>

**Comment by arturovt** [comment] 2022-11-23 07:41
I ain't able to install dependencies in your workspace because of `@labshare/viv` package.

**Comment by robertmazzo** [comment] 2023-01-12 15:18
@abf7d  Hi, what was the final result here? I'm currently struggling with Angular 13 custom webpack on a similar issue. In my case I'm only trying to implement the Azure Event Hub typescript or javascript client.

**Comment by abf7d** [comment] 2023-01-12 22:26
We never got a good solution to this. Sorry I wish I could be of more help.

**Comment by arturovt** [comment] 2024-02-01 18:14
Closing since not able to run the reproducible example and the comment has never been responded.

**Closed by arturovt** 2024-02-01 18:14 UTC
