### ISSUE TITLE
Schema validation fails: Data path "" should NOT have additional properties(customWebpackConfig)

### ISSUE THREAD

**Issue by iliyahanev** [just-jeb/angular-builders#934] opened 2021-02-13 11:27 UTC
**Following up the latest README.md got the error:**
```
> ng serve

Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(customWebpackConfig).`
 ```

**Details about my setup and project:**
Package.json
```
  "dependencies": {
    "@angular-builders/custom-webpack": "^11.0.0",
    "@angular/animations": "~11.2.0",
    "@angular/common": "~11.2.0",
    "@angular/compiler": "~11.2.0",
    "@angular/core": "~11.2.0",
    "@angular/forms": "~11.2.0",
    "@angular/localize": "~11.2.0",
    "@angular/platform-browser": "~11.2.0",
    "@angular/platform-browser-dynamic": "~11.2.0",
    "@angular/router": "~11.2.0",
    "@auth0/auth0-angular": "^1.3.2",
    "@ng-bootstrap/ng-bootstrap": "^8.0.4",
    "axios": "^0.21.1",
    "bootstrap": "^4.5.0",
    "express": "^4.17.1",
    "express-jwt": "^6.0.0",
    "jwks-rsa": "^1.12.2",
    "rxjs": "~6.6.3",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.0",
    "@angular/cli": "~11.2.0",
    "@angular/compiler-cli": "~11.2.0",
    "@types/node": "^12.11.1",
    "apply-loader": "^2.0.0",
    "pug": "^2.0.4",
    "pug-loader": "^2.4.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.5"
  }
```

ng --version
```
Angular CLI: 11.2.0
Node: 12.18.0
OS: darwin x64 (macOS)

Angular: 11.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.0
@angular-devkit/build-angular   0.1102.0
@angular-devkit/core            11.2.0
@angular-devkit/schematics      11.2.0
@schematics/angular             11.2.0
@schematics/update              0.1102.0
rxjs                            6.6.3
typescript                      4.1.5
```

angular.json (arhitect json)
```
 "architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "./extra-webpack.config.js",
              "mergeRules": {
                "module.rules": "prepend"
              },
              "replaceDuplicatePlugins": true
            },
            "outputPath": "dist/myproject",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": true,
            "assets": ["src/favicon.ico", "src/assets"],
            "styles": [
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "src/styles.less"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-builders/custom-webpack:dev-server",
          "options": {
            "customWebpackConfig": {
              "path": "./extra-webpack.config.js",
              "mergeRules": {
                "module.rules": "prepend"
              },
              "replaceDuplicatePlugins": true
            },
            "browserTarget": "myproject:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "myproject:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-builders/custom-webpack:extract-i18n",
          "options": {
            "customWebpackConfig": {
              "path": "./extra-webpack.config.js",
              "mergeRules": {
                "module.rules": "prepend"
              },
              "replaceDuplicatePlugins": true
            },
            "browserTarget": "myproject:build"
          }
        }
      }
```
      
ng serve command:
```
> ng serve

Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(customWebpackConfig).`
 ```

**Comment by just-jeb** [comment] 2021-02-14 15:37
Could you please try regenerating package lock?

**Comment by just-jeb** [comment] 2021-02-14 16:20
Seems like a duplicate of #924 (same root cause).  
A quick fix has been provided in `v11.1.0-beta.1`, would you mind trying it out?

**Comment by iliyahanev** [comment] 2021-02-14 16:50
Hi, How am I able to test it on v11.1.0-beta.1?

**Comment by iliyahanev** [comment] 2021-02-14 17:03
````
> ng serve

        "serve": {
          "builder": "@angular-builders/custom-webpack:dev-server",
          "options": {
            "customWebpackConfig": {
              "path": "./extra-webpack.config.js",
              "mergeRules": {
                "module.rules": "prepend"
              },
              "replaceDuplicatePlugins": true
            },
            "browserTarget": "abidors-webapp:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "abidors-webapp:build:production"
            }
          }
        },

npm start>
ng serve
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(customWebpackConfig).


package json
  "dependencies": {
    "@angular-builders/custom-webpack": "^11.1.0-beta.1",
    "@angular/animations": "~11.2.0",
    "@angular/common": "~11.2.0",
    "@angular/compiler": "~11.2.0",
    "@angular/core": "~11.2.0",
    "@angular/forms": "~11.2.0",
    "@angular/localize": "~11.2.0",
    "@angular/platform-browser": "~11.2.0",
    "@angular/platform-browser-dynamic": "~11.2.0",
    "@angular/router": "~11.2.0",
    "@auth0/auth0-angular": "^1.3.2",
    "@ng-bootstrap/ng-bootstrap": "^8.0.4",
    "axios": "^0.21.1",
    "bootstrap": "^4.5.0",
    "express": "^4.17.1",
    "express-jwt": "^6.0.0",
    "jwks-rsa": "^1.12.2",
    "rxjs": "~6.6.3",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
````

**Comment by just-jeb** [comment] 2021-02-14 19:15
Can you create a minimal reproduction?

**Comment by just-jeb** [comment] 2021-02-14 19:20
Ok I know what the problem is. It's enough to define `customWebpackConfig` in `browser` target. `serve` target (`custom-webpack:dev-server` builder) will read the config from `browser` target. The error you get is actually correct - `dev-server` builder does not support `customWebpackConfig` property.

**Closed** 2021-02-16 15:24 UTC
