### ISSUE TITLE
`showCircularDependencies : false` doesn't work with custom-webpack builder

### ISSUE THREAD

**Issue by mrahhal** [just-jeb/angular-builders#693] opened 2020-03-04 06:59 UTC
## Describe the Bug

`showCircularDependencies : false` doesn't work with custom-webpack builder.

## Minimal Reproduction

Repro: https://github.com/mrahhal/disable-circular-dependencies-problem

This is a standard angular app which I only changed to include @angular-builders/custom-webpack instead of @angular-devkit/build-angular. I also added a simple circular dependency.

I disabled circular dependencies like this:

![image](https://user-images.githubusercontent.com/4404199/75853022-e646ed00-5df5-11ea-8ca7-cd2cc97ecca8.png)

But they still show up:

![image](https://user-images.githubusercontent.com/4404199/75853071-fd85da80-5df5-11ea-9d67-42c674567aac.png)

If I remove custom-webpack builder and add the old @angular-devkit/build-angular, then the warnings are properly hidden:

![image](https://user-images.githubusercontent.com/4404199/75853118-18f0e580-5df6-11ea-8012-3ae1f01b7027.png)

## Environment

<pre><code>- @angular/core version: 9.0.2
- @angular-devkit/build-angular version: 0.900.3
- @angular-builders/custom-webpack version: 9.0.0 (latest)

**Comment by just-jeb** [comment] 2020-03-05 12:48
Sounds very [familiar](https://github.com/just-jeb/angular-builders/issues/422). Is it the same issue? If yes then you have a workaround in the thread I mentioned and an open issue in [Angular CLI repo](https://github.com/angular/angular-cli/issues/16098).

**Comment by mrahhal** [comment] 2020-03-05 13:07
Yeah seems to be the same problem. It appears you might want this issue, but feel free to close it otherwise. I'll be tracking angular/angular-cli#16098 as well. Thanks.

**Comment by just-jeb** [comment] 2020-03-05 13:26
Seems pretty much like a duplicate of #422 so I'm gonna close it. Please let me know if the workaround worked for you.

**Closed by just-jeb** 2020-03-05 13:26 UTC

**Comment by mrahhal** [comment] 2020-03-05 13:44
The following inside my custom webpack file worked great:

```javascript
module.exports = (config) => {
	config.plugins = config.plugins.filter(plugin => plugin && !plugin.constructor.name.includes("CircularDependency"));

	return config;
};
```
