### ISSUE TITLE
Service worker generation failed. Angular 13 upgrade

### ISSUE THREAD

**Issue by blueiceprj** [just-jeb/angular-builders#1050] opened 2021-11-04 10:48 UTC
I get this error message on build after updating to angular version 13. You can look at from here.

[Angular issue](https://github.com/angular/angular/issues/44051)

**Comment by abadakhshan** [comment] 2021-11-04 15:09
@blueiceprj 

It's related to the dependencies of @angular-builders/custom-webpack

I described it here before.

#930 

The temporary solution should be deleting `node-modules` from `node_modules\@angular-builders\custom-webpack`

**Comment by blueiceprj** [comment] 2021-11-04 15:27
I use custom webpack builder on my project. I can't do that.

**Comment by alejandroaap** [comment] 2021-11-04 15:49
@abadakhshan After deleting that folder I am getting the following error An unhandled exception occurred: Cannot destructure property 'styles' of 'buildOptions.sourceMap' as it is undefined.

**Comment by abadakhshan** [comment] 2021-11-04 15:51
> I use custom webpack builder on my project. I can't do that.

Don't delete `node_modules\@angular-builders\custom-webpack`

You just should delete `node_modules\@angular-builders\custom-webpack\node-modules`

**Comment by abadakhshan** [comment] 2021-11-04 15:57
> @abadakhshan After deleting that folder I am getting the following error An unhandled exception occurred: Cannot destructure property 'styles' of 'buildOptions.sourceMap' as it is undefined.

@alejandroaap 
Yes, You are exactly when I am.

I found what is the root cause of this error and I  am trying to fix it.

If you check the   `node-modules\@angular-devkit\architect` version, you found that the version is 0.1202.13. But it should be 0.1300.1.

It could be a side-effect of version conflict. 

I'm still on it to solve the problem.

**Comment by alejandroaap** [comment] 2021-11-04 16:34
@abadakhshan Thanks for your reply. Hopefully the merger doesn't delay. Greetings

**Comment by just-jeb** [comment] 2021-11-04 16:48
Hey guys! Yeah you're absolutely right, the issue will be resolved once the builders are update to Angular 13 (the major versions should always match).
Currently there is some issue with Jest builder, the guys from `jest-preset-angular` are working on resolving it.
I expect the PR to be merged in the next few days, stay tuned.

**Closed by just-jeb** 2021-11-04 16:48 UTC

**Comment by blueiceprj** [comment] 2021-11-04 17:25
> > I use custom webpack builder on my project. I can't do that.
> 
> Don't delete `node_modules\@angular-builders\custom-webpack`
> 
> You just should delete `node_modules\@angular-builders\custom-webpack\node-modules`

Firstly I remove this folder and getting this error.

An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular'
```
Require stack:
- uaa-ui/node_modules/@angular-builders/custom-webpack/dist/browser/index.js
- uaa-ui/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- uaa-ui/node_modules/@angular-devkit/architect/node/index.js
- uaa-ui/node_modules/@angular/cli/models/architect-command.js
-uaa-ui/node_modules/@angular/cli/commands/build-impl.js
- uaa-ui/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /uaa-ui/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /uaa-ui/node_modules/@angular/cli/utilities/json-schema.js
- /uaa-ui/node_modules/@angular/cli/models/command-runner.js
- /uaa-ui/node_modules/@angular/cli/lib/cli/index.js
- /uaa-ui/node_modules/@angular/cli/lib/init.js
See "/private/var/folders/n1/0rhwf_mj3gq7lk0jkd5gtk3h0000gn/T/ng-cgj51A/angular-errors.log" for further details.
```
