### ISSUE TITLE
@angular-builders/custom-webpack breaks karma tests

### ISSUE THREAD

**Issue by annamichalik** [just-jeb/angular-builders#1562] opened 2023-11-24 09:15 UTC
## Describe the Bug
After adding  package "@angular-builders/custom-webpack": "^14.1.0" and  configuring angular.json  -only build part  - the tests stopped working ( No specs found,)
"architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "src/extra-webpack.config.js",
              "mergeRules": {
                "externals": "replace"
              }
            },

## Minimal Reproduction
node version
1.) clone https://github.com/annamichalik/Angular14withEslint/tree/main
2.) Run : npm install
 3. )Run :  npm test
 You see result : 
```
> angular-eslint@0.0.0 test
> ng test

√ Browser application bundle generation complete.

./src/app/app.component.spec.ts:1:0-171 - Error: Module not found: Error: Can't resolve 'D:/dev/myGithub/Angular14withEslint/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js' in 'D:\dev\myGithub\Angular14withEslint\src\app'

./node_modules/@angular/core/fesm2020/testing.mjs:1:0-171 - Error: Module not found: Error: Can't resolve 'D:/dev/myGithub/Angular14withEslint/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js' in 'D:\dev\myGithub\Angular14withEslint\node_modules\@angular\core\fesm2020'
```

https://github.com/annamichalik/Angular14withEslint/tree/main

## Expected Behavior
Test should run as in new Angular 14 application.
## Screenshots
![2023-11-24 10_01_40-ng testcustom-webpackIssue](https://github.com/just-jeb/angular-builders/assets/8555072/a4eb36d6-0405-45d0-b3d2-0c7d54a33fda)

## Environment

<pre><code>
Libs
- @angular/core@14.3.0 
-  @angular-devkit/build-angular@14.2.13 
- @angular-builders/custom-webpack@14.1.0 

For Tooling issues:
- Node version: v18.18.2
- Platform:  Windows 

## Additional Context

I had to use @angular-builders/custom-webpack in order to clear jsPDF warning : https://github.com/parallax/jsPDF/issues/3144

**Comment by annamichalik** [comment] 2023-11-24 10:29
It could be a cache issue - it cannot be reproduced on clear clone project

**Comment by annamichalik** [comment] 2023-11-24 12:24
I cannot preproduce it

**Comment by arturovt** [comment] 2024-02-01 17:20
Closing since not reproducible.

**Closed by arturovt** 2024-02-01 17:20 UTC
