### ISSUE TITLE
@angular-builders/custom-webpack:browser fails with angular 9.1

### ISSUE THREAD

**Issue by paul58914080** [just-jeb/angular-builders#710] opened 2020-03-29 17:45 UTC
## Describe the Bug

Tried to use @angular/cli v9.1 which has typescript 3.8 and when I tried to perform ng build using @angular-builders/custom-webpack:browser it fails with error

```
ERROR in Cannot read property 'flags' of undefined
```

## Minimal Reproduction

1. Checkout https://github.com/devs-from-matrix/ff4j-web-console
2. `yarn install`
3. `yarn run build:features-element`

## Expected Behavior

Should generate build files

## Environment

<pre><code>
Libs
- @angular/core version: 9.1.0
- @angular-devkit/build-angular version: ~0.901.0
- @angular-builders/custom-webpack version: 9.0.0

For Tooling issues:
- Node version: v13.8.0
- Platform:  Mac

**Comment by just-jeb** [comment] 2020-03-29 18:09
Probably the same as [this](https://github.com/just-jeb/angular-builders/issues/708). Would you mind trying `v9.1.0-beta.1`?

**Comment by adover** [comment] 2020-03-29 23:40
@just-jeb I tried that and it did not work unfortunately

**Comment by paul58914080** [comment] 2020-03-30 02:46
@just-jeb the version `v9.1.0-beta.1` seem to have fixed the issue for me.

**Comment by just-jeb** [comment] 2020-03-30 07:17
@adover could you please share your `package.json` and `package-lock.json`?

**Comment by adover** [comment] 2020-03-30 07:23
Of course! Here you go @just-jeb 

```
"dependencies": {
		"@angular/animations": "^9.1.0",
		"@angular/cdk": "^8.1.4",
		"@angular/common": "^9.1.0",
		"@angular/compiler": "^9.1.0",
		"@angular/core": "^9.1.0",
		"@angular/elements": "^9.1.0",
		"@angular/forms": "^9.1.0",
		"@angular/localize": "^9.1.0",
		"@angular/platform-browser": "^9.1.0",
		"@angular/platform-browser-dynamic": "^9.1.0",
		"@angular/router": "^9.1.0",
		"@angular/service-worker": "^9.1.0",
		"@commitlint/config-conventional": "^8.1.0",
		"@microsoft/applicationinsights-web": "^2.2.0",
		"@ngrx/effects": "8.3.0",
		"@ngrx/router-store": "8.3.0",
		"@ngrx/store": "8.3.0",
		"@nrwl/nx": "^7.8.7",
		"@webcomponents/custom-elements": "^1.2.4",
		"@webcomponents/webcomponentsjs": "^2.2.10",
		"classlist.js": "1.1.20150312",
		"core-js": "^3.1.3",
		"cpx": "^1.5.0",
		"dayjs": "^1.8.19",
		"document-register-element": "^1.13.2",
		"elements-zone-strategy": "^8.0.0",
		"fast-deep-equal": "^3.1.1",
		"global": "^4.4.0",
		"hammerjs": "^2.0.8",
		"html-minifier": "^4.0.0",
		"http-status-codes": "^1.4.0",
		"npm": "^6.14.4",
		"postcss-preset-env": "^6.7.0",
		"raw-loader": "^1.0.0",
		"rxjs": "~6.5.2",
		"shx": "^0.3.2",
		"svg-sprite": "^1.5.0",
		"take-until-destroy": "^2.1.0",
		"terser": "3.14.1",
		"tslib": "^1.10.0",
		"web-animations-js": "^2.3.2",
		"zone.js": "~0.10.2"
	},
	"devDependencies": {
		"@angular-builders/custom-webpack": "^9.1.0-beta.1",
		"@angular-builders/dev-server": "^7.3.1",
		"@angular-builders/jest": "^9.0.0",
		"@angular-devkit/build-angular": "~0.901.0",
		"@angular-devkit/build-ng-packagr": "~0.901.0",
		"@angular/cli": "9.1.0",
		"@angular/compiler-cli": "^9.1.0",
		"@angular/language-service": "^9.1.0",
		"@babel/core": "^7.8.3",
		"@babel/plugin-proposal-decorators": "^7.8.3",
		"@babel/preset-env": "^7.8.3",
		"@ngrx/schematics": "8.6.0",
		"@ngrx/store-devtools": "8.3.0",
		"@nrwl/builders": "^7.8.7",
		"@nrwl/cypress": "^8.11.2",
		"@nrwl/jest": "8.11.2",
		"@nrwl/schematics": "^8.12.11",
		"@percy/storybook": "^3.2.0",
		"@storybook/addon-a11y": "^5.3.17",
		"@storybook/addon-actions": "^5.3.17",
		"@storybook/addon-backgrounds": "^5.3.17",
		"@storybook/addon-centered": "^5.3.17",
		"@storybook/addon-cssresources": "^5.3.17",
		"@storybook/addon-docs": "^5.2.3",
		"@storybook/addon-events": "^5.3.17",
		"@storybook/addon-jest": "^5.3.17",
		"@storybook/addon-knobs": "^5.3.17",
		"@storybook/addon-links": "^5.3.17",
		"@storybook/addon-notes": "^5.3.17",
		"@storybook/addon-options": "^5.3.17",
		"@storybook/addon-storyshots": "^5.3.17",
		"@storybook/addon-storyshots-puppeteer": "^5.3.17",
		"@storybook/addon-storysource": "^5.3.17",
		"@storybook/addon-viewport": "^5.3.17",
		"@storybook/addons": "^5.3.17",
		"@storybook/angular": "^5.3.17",
		"@storybook/source-loader": "^5.3.17",
		"@types/jest": "^24.0.18",
		"@types/jest-environment-puppeteer": "^4.0.0",
		"@types/jest-image-snapshot": "^2.8.0",
		"@types/jquery": "3.3.30",
		"@types/node": "^12.11.1",
		"@types/storybook__addon-actions": "^3.4.3",
		"agentkeepalive": "^3.5.2",
		"babel-jest": "^24.9.0",
		"babel-loader": "^8.0.6",
		"babel-plugin-require-context-hook": "^1.0.0",
		"base64-inline-loader": "^1.1.1",
		"clean-webpack-plugin": "^3.0.0",
		"codelyzer": "^5.1.2",
		"cross-env": "^5.2.0",
		"css-loader": "^1.0.1",
		"cssnano": "^4.1.10",
		"cssnano-preset-advanced": "^4.0.7",
		"cypress": "^3.4.1",
		"cypress-image-snapshot": "^3.1.1",
		"cz-conventional-changelog": "^2.1.0",
		"debug": "^4.1.1",
		"dotenv": "^8.0.0",
		"html-webpack-plugin": "^3.2.0",
		"husky": "^3.0.0",
		"jasmine-marbles": "0.6.0",
		"jest": "^24.9.0",
		"jest-image-snapshot": "^2.9.0",
		"jest-preset-angular": "7.1.1",
		"jest-puppeteer": "^4.3.0",
		"mini-css-extract-plugin": "^0.8.0",
		"minimist": "^1.2.5",
		"ng-packagr": "^9.0.0",
		"ngrx-store-freeze": "0.2.4",
		"ngx-markdown": "^8.1.0",
		"ngx-schematics-for-storybook": "^0.2.2",
		"node-sass": "^4.13.1",
		"node-sass-utils": "^1.1.2",
		"optimize-css-assets-webpack-plugin": "^5.0.3",
		"perfume.js": "^4.8.1",
		"postcss-loader": "^3.0.0",
		"prettier": "1.18.2",
		"puppeteer": "^1.19.0",
		"sass-export": "^1.0.4",
		"sass-loader": "^7.1.0",
		"sassdoc": "^2.7.0",
		"scss-bundle": "^2.5.1",
		"scss-comment-parser": "^0.8.4",
		"source-map-explorer": "^2.0.1",
		"start-server-and-test": "^1.9.1",
		"style-loader": "^0.23.1",
		"stylelint": "^10.0.1",
		"stylelint-config-prettier": "^6.0.0",
		"stylelint-config-recommended": "^2.2.0",
		"stylelint-config-recommended-scss": "^3.3.0",
		"stylelint-order": "^3.0.1",
		"stylelint-prettier": "^1.1.1",
		"stylelint-scss": "^3.9.1",
		"svgo": "^1.3.0",
		"ts-jest": "^24.0.2",
		"ts-node": "~8.3.0",
		"tsconfig-paths-webpack-plugin": "^3.2.0",
		"tslint": "~6.0.0",
		"tslint-config-prettier": "^1.18.0",
		"tslint-plugin-prettier": "^2.0.1",
		"typescript": "^3.8.3",
		"url-loader": "^2.0.1",
		"webpack-bundle-analyzer": "^3.3.2",
		"webpack-cli": "^3.3.6",
		"webpack-concat-plugin": "^3.0.0"
	}
```

[package-lock.json.txt](https://github.com/just-jeb/angular-builders/files/4401348/package-lock.json.txt)

**Comment by just-jeb** [comment] 2020-03-30 11:56
@adover Ok, as far as I can tell (judging by your `package-lock.json`) the problem is that you use `@angular-builders/jest@9.0.0` which requires `@angular-devkit/architect@0.900.0`, which, in turn, prevents from `@angular-builders/custom-webpack` using the topmost `@angular-devkit` instance (`0.901.0`).  
Changing the version to `@angular-builders/jest@9.0.1-beta.2` should fix your problem.

In general I see a lot of noise in your setup which creates versions misalignment (although I might not know all the details). For example:  

 - You use `nrwl/angular@8` which requires `@angular-devkit/*@8`, 
- `nrwl/builders@7` which requires even earlier version of `@angular-devkit`

And more like this.  

I'd highly recommend you to align all the versions across all the packages you use.

Btw you also don't need `@angular-builders/dev-server` anymore, it's part of `custom-webpack` since version 8.

**Comment by adover** [comment] 2020-03-30 19:59
Thanks for the insight @just-jeb , very informative! I've updated all of those but spotted `@nrwl/cypress` also requires the outdated architect version. There's a PR open for that so I'll wait until it's through before coming back to you.

**Comment by sidv93** [comment] 2020-03-31 07:03
Hi @just-jeb ,
I tried using the `v9.1.0-beta.1` version and unfortunately, the build fails.

Here is a sample repo [Repo](https://github.com/sidv93/ng-builders-test) with a freshly generated cli project and a simple webpack config file.

### Error:
![image](https://user-images.githubusercontent.com/32375112/77996320-0614f680-734b-11ea-9d1f-4e67f506eb69.png)

Any help appreciated!

**Comment by just-jeb** [comment] 2020-03-31 07:36
@sidv93 I checked out your repo. According to package-lock.json you don't have a version mismatch, so it's probably unrelated to this specific issue.  
I think it's your configuration that is problematic. What if you just use `custom-webpack:browser` builder without any custom webpack config/merge strategies?

**Comment by sidv93** [comment] 2020-03-31 14:22
Hey @just-jeb, it seems to be a configuration issue, not a version mismatch. Thank you for your help.

**Comment by adover** [comment] 2020-03-31 19:20
Hi @just-jeb 

I updated my packages and tidied things up but it seems I am still getting the issue. I ended up having to manually add @angular-devkit/architect at 0.901.0 also, as it kept showing up as 0.907.0.

Here's my package-lock.
[package-lock.json.txt](https://github.com/just-jeb/angular-builders/files/4411148/package-lock.json.txt)

Error message is still the same

```
ERROR in polyfills-es5.js from Terser
Invalid assignment [polyfills-es5.js:1,17]
```

**Comment by just-jeb** [comment] 2020-04-02 08:33
By `0.907.0` you meant `0.900.7` I guess? You shouldn't be adding it manually in any case if you do so it's a problem.  
Anyways, I don't see a version mismatch in your package-lock so it's not related to this specific issue. Would you mind creating another issue with a clear description and steps to reproduce?  
I'm closing this one as solved.

**Closed by just-jeb** 2020-04-02 08:33 UTC
