### ISSUE TITLE
CustomWebpack with Devkit/CLI 8.2 causes build options to get overridden/ignored

### ISSUE THREAD

**Issue by justinappler** [just-jeb/angular-builders#422] opened 2019-08-01 17:45 UTC
**Update**:
Related issue in Angular CLI repo: https://github.com/angular/angular-cli/issues/16098

**Describe the bug**
This is a hard bug to describe, but when using custom-webpack for both dev-server and browser, certain options in the browser build get ignored. I spent a lot of time trying to debug what's going on (the devkit was *very* hard to debug), and it seems that when getTargetOptions is called within custom-webpack/dev-server, it includes the options, but when getTargetOptions is called *again* inside of `executeDevServerBuilder`, it is missing some of the options specified.

This manifested for me with 'showCircularDependencies' (which is set to false for my browser build) getting ignored in the dev server build but respected in the browser build).]

This seems to repro pretty easily by simply calling `getTargetOptions` twice inside of [dev server](https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/src/dev-server/index.ts#L11), e.g.

```
    async function setup() {
        const browserTarget = targetFromTargetString(options.browserTarget);

        const targetOptions1 = context.getTargetOptions(browserTarget).then(opts => // correct);
        const targetOptions2 = context.getTargetOptions(browserTarget).then(opts => // missing some parameters)

        return context.getTargetOptions(browserTarget) as unknown as CustomWebpackSchema;
    }
```

I hope this is enough to investigate, I can provide more details as well

**To Reproduce**
1. Create a project that uses dev-server
2. Add a non-default property to the browser build, e.g. `showCircularDependencies: false`
3. Target dev-server at build:browser
4. Notice that the property showCircularDeps is ignored

**Expected behavior**
Properties specified in the browser build are ignored

**Libraries**
```
@angular-builders/custom-webpack: "8.1.0"
@angular-devkit/architect: "0.802.0"
@angular-devkit/build-angular: "0.802.0"
@angular-devkit/build-optimizer: "0.802.0"
@angular/cli: "8.2.0"
@angular/compiler-cli: "8.2.0"
@angular/language-service: "8.2.0"
```

**Comment by anhkind** [comment] 2019-08-06 19:06
I got exactly the same issue with `showCircularDependencies: false` being ignored completely in `dev-server` target. Any ideas how to fix this yet?

**Comment by justinappler** [comment] 2019-08-15 16:25
Haven't had a chance to test it yet, but this may have been fixed in https://github.com/angular/angular-cli/pull/15328

**Comment by just-jeb** [comment] 2019-08-17 15:47
Please update me if this is still the case with `custom-webpack@8.2.0`.

**Comment by chriswep** [comment] 2019-08-19 13:57
> Please update me if this is still the case with `custom-webpack@8.2.0`.

it's still the case for me

**Comment by kqadem** [comment] 2019-08-23 09:16
The problem here is that @angular-builders will apply its config onto the base webpack config. This was okay, because the CLI webpack-config has been applied **before** the custom one.
But this [Commit](https://github.com/angular/angular-cli/commit/f1f49325f776d2ab2ee1074c81b1d20e2da927da#diff-0290ce657e1aab8b5ffc2df31519b1a9) changed the behaviour.

On a quick look into the [code](https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/src/custom-webpack-builder.ts#L20) I'd assume that using `mergeConfigs` in both cases might solve the issue, but I think there was a reason the differ when providing a function. I donno :confused:

**Comment by justinappler** [comment] 2019-09-06 16:52
@just-jeb Tried again updating to latest CLI/Devkit, the problem seems to persist.

**Comment by just-jeb** [comment] 2019-09-06 17:13
@flash-me the code (both Angular's and custom-webpack') seems completely fine to me. The custom config is still applied after the base one - note that the base one is passed to a transform, which, in turn, merges the config while the custom overrides the base.   
Regarding the `if`, yes, you are right, this is for reason. If custom config exports a function, the base config is passed into this function and then the function is supposed to modify it and return the new config. It's described in the docs.  
I'll try to figure out why you're getting this weird behavior, but from the first glance the code seems OK. 
One thing I need you to try though. If you run the dev-server build with `aot` the problem still persists?

**Comment by flash-me** [comment] 2019-09-06 19:20
@just-jeb Uhhhm puhh. Donno what exactly the issue was here. In the meanwhile I changed my approach / have my own builders. 
I think the problem was a mix of "where do I have to write what" like in `angular.json` you set flags for the CLI 
and in `webpack.custom.config.js` you are modifying the final `WebpackOptions` that will be used to execute webpack in the end with the help of `ExecutionTransformer`.

But all in all, just checked again. Seems to work for me. :+1: 
I'm dealing with other [issues atm](https://github.com/angular/angular-cli/issues/15547) ^^

**Comment by just-jeb** [comment] 2019-09-06 19:29
I see. Seems that I also misunderstood the issue.  
@justinappler , @chriswep Just to make sure I understand it right:
1. You use some non-default option in `browser` build in `angular.json` (for example `showCircularDependencies: false`).
2. When you use vanilla builders (`@angular-devkit/build-angular`) it works as expected both for `build` and `serve`.
3. When you use `@angular-builders/custom-webpack`, without even using custom webpack config (just replacing the builder) causing the `serve` to ignore this override. 
Is that so?  
Would you mind creating a minimal reproduction repo for me?

**Comment by justinappler** [comment] 2019-09-06 20:26
@just-jeb OK, simple repro repo: https://github.com/justinappler/custom-builder-repro-case

If you switch out the custom builders for the devkit versions, the `showCircularDependencies` flag will be respected.

**Comment by just-jeb** [comment] 2019-09-13 13:42
@justinappler thank you for investing time in investigation, it really helped me. I confirm the issue - two subsequent calls to `context.getTargetOptions` return different results.  
However, the problem is within Angular Devkit (I did the subsequent call in their code and it still reproduces). Trying to figure out with Angular team what's the root cause.  
@mancmanomyst Since the problem is within Angular I don't see it resolved before they release the next version of Devkit. So you'll probably have to wait, sorry. Can you try different `0.80x.0` versions of the devkit? If the problem was introduced in one of the minor releases you would be able to upgrade to Angular 8 (just not the latest one).  
I'll update once I have more info.

**Comment by justinappler** [comment] 2019-09-16 17:53
@just-jeb Is there an issue filed in the cli repo or something else we should track?

**Comment by just-jeb** [comment] 2019-09-16 18:09
I asked on Slack channel but didn't get any answer yet. 
Wanted to open an issue once I have more info on this. 
Narrowed it down to here meanwhile: https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/architect/node/node-modules-architect-host.ts#L102
The options returned from this function are different in subsequent calls. It's probably some problem with Workspace, didn't get to it yet.  
You are welcome to open an issue though in Angular CLI repo. Otherwise I'll file it once I have time to get to the root cause.

**Comment by just-jeb** [comment] 2019-09-18 06:52
Ok guys, I might have a reasonable workaround for you if your issue is just the `showCircularDependencies` flag. They [use](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L235) `CircularDependencyPlugin` in Angualr CLI, so until the issue is fixed you can re-define `CircularDependencyPlugin` with your own excludes:
```
plugins: [
      new CircularDependencyPlugin({
        exclude: /your regex here/,
      }),
]
```

**Comment by chriswep** [comment] 2019-09-18 08:22
@just-jeb i tried this but strangely it doesn't remove the warnings coming from my own codebase (i even tried `.*` regex). if i run it without excludes it shows warnings from node_modules also (which it didn't without the custom plugin) - however excluding those works.

**Comment by just-jeb** [comment] 2019-09-18 08:29
@chriswep Interesting... Would you mind trying it with `overrideDuplicatePlugins` option?

**Comment by chriswep** [comment] 2019-09-18 08:36
googling the term `"overrideDuplicatePlugins"` returns zero results (which is surprising for such a non-random word :-)  -  is this the correct option / how/where do i use it?

**Comment by just-jeb** [comment] 2019-09-18 08:44
It's an option of custom-webpack builder, the docs are [here](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack#custom-webpack-config-object).

**Comment by chriswep** [comment] 2019-09-18 08:52
unfortunately this has no effect on the problem:

```
"customWebpackConfig": {
   "path": "./webpack.config.js",
   "overrideDuplicatePlugins": true
}
```

i also tried `replaceDuplicatePlugins` (which is mentioned in the docs and probably what you meant)

**Comment by just-jeb** [comment] 2019-09-18 09:10
Yeah, sorry, that's what I meant.
Any chance that your regex is wrong? Would you mind sharing it here?
The thing that would work for sure (if you want to exclude all the files in the project) is completely  removing the `CircularDependencyPlugin` from the plugins array. For that you can use [custom webpack config function](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack#custom-webpack-config-function). Just find the plugin by constructor name and remove it from the array.  
But I'd first try playing with the regex.

**Comment by chriswep** [comment] 2019-09-18 09:14
> Any chance that your regex is wrong? 
Of course :-)

that's the warning
```
[ng] WARNING in Circular dependency detected:
[ng] ../shared/src/courses/entities/Content.entity.ts -> ../shared/src/courses/entities/ContentData.entity.ts -> ../shared/src/courses/entities/Content.entity.ts
```

that's my regex: `exclude: /node_modules|entities/`
As i said, i also tried `.*` to be sure

Can't see why that shouldn't work but that doesn't mean it isn't there.

**Comment by mancmanomyst** [comment] 2019-09-18 18:00
@chriswep try /[\s\S]*/

It's worked for me.

Thanks @justinappler for the workaround.

Just in case any newbs to webpack like me come across this,

you need to run npm install --save circular-dependency-plugin if you haven't already got it installed and also require it i.e. const CircularDependencyPlugin = require('circular-dependency-plugin');

Then this will work
```
module.exports = {
	plugins: [
	new CircularDependencyPlugin({
		exclude: /[\s\S]*/,
	})]
}
```

**Comment by chriswep** [comment] 2019-09-19 08:38
> @chriswep try /[\s\S]*/

Unfortunately i still see the warnings.

Wonder if i'm missing something obvious here. However the fact that my plugin override has an effect (e.g. if i remove the exclude option for node_modules) let's me think otherwise.

**Comment by chriswep** [comment] 2019-09-19 09:00
> The thing that would work for sure (if you want to exclude all the files in the project) is completely removing the CircularDependencyPlugin from the plugins array. For that you can use custom webpack config function. 

@just-jeb thing is i was using the a custom webpack config all along (thus disabling the merging and/or plugin-replacing of CustomWebpack as i learned now). So removing the CircularDependencyPlugin finally did the trick:

```
    config.plugins = config.plugins.filter(plugin => !(plugin instanceof CircularDependencyPlugin));
    config.plugins.push(
        new CircularDependencyPlugin({
            exclude: /node_modules|shared/
        })
    );
```

**Comment by justinappler** [comment] 2019-09-23 19:37
@just-jeb It looks like the Circular Dependency problem isn't the only one. I've also now noticed that, likely a similar reason, differential loading in production builds isn't working properly when I use the custom builder. Angular doesn't produce the proper es2015 builds and thus the differential loading code doesn't get run (I then get runtime errors when using es2015 features).

**Comment by just-jeb** [comment] 2019-09-23 19:39
That's weird. Mind sharing your config?

**Comment by justinappler** [comment] 2019-09-23 19:57
@just-jeb Angular.json is here: https://gist.github.com/justinappler/b5e7decef5f1788842921a5640461d8b I think this is a side effect of the internal webpack config created by Angular not getting respected. I noticed that chunkFilenames are ignored as well and had to add those back. Specifically what I'm seeing is that when I used the stock builders, I get a `main-es2015` and `main-es5` bundle. With custom builders, I only get a main bundle and that bundle doesn't have certain polyfills (concerning)

**Comment by just-jeb** [comment] 2019-09-23 19:59
Does this problem appear only with dev-server builder or also with browser?
What your custom config looks like?

**Comment by justinappler** [comment] 2019-09-23 20:01
I'm seeing this in the production configuration of the browser builder. Extra webpack file looks like:
```
module.exports = (config) => {

  config.node = {
    path: true,
    process: 'mock',
    global: true
  };

  config.plugins = config.plugins.filter(plugin => plugin && !plugin.constructor.name.includes("CircularDependency"));

  return config;
};
```

**Comment by just-jeb** [comment] 2019-09-23 20:07
What about development configuration of browser?

**Comment by justinappler** [comment] 2019-09-23 20:28
Same issue, generates a single `main.hash.js` bundle instead of the `main-es2015` and `main-es5`.

**Comment by JulianH** [comment] 2019-11-07 12:52
@justinappler, @just-jeb, i've raised an issue in the angular-cli repo: https://github.com/angular/angular-cli/issues/16098 which should address the problem.
If you have more informations, please add them to the ticket.

**Comment by just-jeb** [comment] 2019-11-07 13:24
I forgot to update this issue, but two weeks ago I had a conversation with one of the guys for Angular CLI team. Here what he said:
> I have a PR up that should be in the next release that performs a deep clone of the options before passing them to a builder.  I unfortunately haven’t had the time to setup a test scenario but this should hopefully address your issue.  The behavior also has benefits outside of this scenario as well. Builders should not be able to change the underlying configuration objects and potentially break other builders that could be executed.

That means that hopefully with Angular 9 it will be fixed.

**Comment by fasidOnGit** [comment] 2020-05-18 07:04
Alright! that https://github.com/just-jeb/angular-builders/issues/422#issuecomment-532797449 worked!

Thank you @mancmanomyst

**Comment by just-jeb** [comment] 2020-05-18 08:15
There are [rumors](https://github.com/just-jeb/angular-builders/issues/736#issuecomment-628837149) that the issue has been fixed in the latest CLI versions. Could you guys verify that?

**Comment by insin** [comment] 2021-03-26 11:10
I just upgraded an app from Angular 8.x to Angular 11.x and the circular dependency plugin workaround above wasn't needed any more :+1:

**Closed** 2021-04-04 10:54 UTC
Labels: builders:custom-webpack, required:investigation
